### ISSUE TITLE
Suggestion: Apply an OSS license such as MIT so that others may fork, modify, and contribute to this work

### ISSUE THREAD

**Issue by ryanewtaylor** [luciusbono/Packer-Windows81#14]
First, let me apologize if this request comes off as presumptuous, this is not the intent. I am attempting to learn how to use packer, vagrant, and other automated tools to create machine images for my development environments. 

This is one of the cleanest packer examples I have seen and I would like to base my learning/work on this.

Would you be willing to apply an OSS license such as MIT such that I (and others) may fork, modify, and/or contribute to this repository? This is certainly your prerogative and I will understand if you choose to not apply any specific licensing to this work. 

If I am mistaken and a license has been applied, can you point to me to the license?

**Comment by luciusbono** [comment]
Hi! Apologies for the delay in response, I've been on vacation and have been mostly "unplugged". 

Thanks for the incredible compliment! I've been using a less-is-more approach to teach myself more about Packer / Windows config management and a clean build is exactly what I was going for. I hope you find it useful!

I absolutely will include a license in this project in the near future - my intent was for anyone to use this code as they saw fit. I actually need to make sure that I attribute the Windows Update script to Joe Fitzgerald (https://github.com/joefitzgerald/packer-windows) as I made only minor changes to his code. 

Not sure if there is anything else I need to do other than copy an existing MIT license and put it in the root of my project, but I'll add it to the issues in this repo soon. 

In the interim: please contribute to this project any way you see fit! Thanks for using it.

**Comment by luciusbono** [comment]
Done! https://github.com/luciusbono/Packer-Windows81/pull/18

Please feel free to use this code however you see fit - also, I've made some pretty significant changes to this project, which had gotten pretty far out of step with my other Windows packer project https://github.com/luciusbono/Packer-Windows10
